[tool.poetry]
name = "attest"
version = "0.1.0"
description = ""
authors = ["yuliyakuznetsova0102 <juliakuznetsova001@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
dotenv = "^0.9.9"
django = "^5.2.4"
djangorestframework = "^3.16.0"
django-filter = "^25.1"
psycopg2-binary = "^2.9.10"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
isort = "^6.0.1"
mypy = "^1.16.1"
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
